#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCG
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HCG1")]
	public partial class DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertApSuat(ApSuat instance);
    partial void UpdateApSuat(ApSuat instance);
    partial void DeleteApSuat(ApSuat instance);
    partial void InsertVungKhiHau(VungKhiHau instance);
    partial void UpdateVungKhiHau(VungKhiHau instance);
    partial void DeleteVungKhiHau(VungKhiHau instance);
    partial void InsertDataContent(DataContent instance);
    partial void UpdateDataContent(DataContent instance);
    partial void DeleteDataContent(DataContent instance);
    partial void InsertDoAm(DoAm instance);
    partial void UpdateDoAm(DoAm instance);
    partial void DeleteDoAm(DoAm instance);
    partial void InsertGio(Gio instance);
    partial void UpdateGio(Gio instance);
    partial void DeleteGio(Gio instance);
    partial void InsertLogIn(LogIn instance);
    partial void UpdateLogIn(LogIn instance);
    partial void DeleteLogIn(LogIn instance);
    partial void InsertNhietDo(NhietDo instance);
    partial void UpdateNhietDo(NhietDo instance);
    partial void DeleteNhietDo(NhietDo instance);
    partial void InsertRule(Rule instance);
    partial void UpdateRule(Rule instance);
    partial void DeleteRule(Rule instance);
    partial void InsertThoiTiet(ThoiTiet instance);
    partial void UpdateThoiTiet(ThoiTiet instance);
    partial void DeleteThoiTiet(ThoiTiet instance);
    #endregion
		
		public DataContext() : 
				base(global::HCG.Properties.Settings.Default.HCG1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ApSuat> ApSuats
		{
			get
			{
				return this.GetTable<ApSuat>();
			}
		}
		
		public System.Data.Linq.Table<VungKhiHau> VungKhiHaus
		{
			get
			{
				return this.GetTable<VungKhiHau>();
			}
		}
		
		public System.Data.Linq.Table<DataContent> DataContents
		{
			get
			{
				return this.GetTable<DataContent>();
			}
		}
		
		public System.Data.Linq.Table<DoAm> DoAms
		{
			get
			{
				return this.GetTable<DoAm>();
			}
		}
		
		public System.Data.Linq.Table<Gio> Gios
		{
			get
			{
				return this.GetTable<Gio>();
			}
		}
		
		public System.Data.Linq.Table<LogIn> LogIns
		{
			get
			{
				return this.GetTable<LogIn>();
			}
		}
		
		public System.Data.Linq.Table<NhietDo> NhietDos
		{
			get
			{
				return this.GetTable<NhietDo>();
			}
		}
		
		public System.Data.Linq.Table<Rule> Rules
		{
			get
			{
				return this.GetTable<Rule>();
			}
		}
		
		public System.Data.Linq.Table<TAPLUAT> TAPLUATs
		{
			get
			{
				return this.GetTable<TAPLUAT>();
			}
		}
		
		public System.Data.Linq.Table<ThoiTiet> ThoiTiets
		{
			get
			{
				return this.GetTable<ThoiTiet>();
			}
		}
		
		public System.Data.Linq.Table<VUNG1> VUNG1s
		{
			get
			{
				return this.GetTable<VUNG1>();
			}
		}
		
		public System.Data.Linq.Table<VUNG2> VUNG2s
		{
			get
			{
				return this.GetTable<VUNG2>();
			}
		}
		
		public System.Data.Linq.Table<VUNG3> VUNG3s
		{
			get
			{
				return this.GetTable<VUNG3>();
			}
		}
		
		public System.Data.Linq.Table<VUNG4> VUNG4s
		{
			get
			{
				return this.GetTable<VUNG4>();
			}
		}
		
		public System.Data.Linq.Table<VUNG5> VUNG5s
		{
			get
			{
				return this.GetTable<VUNG5>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ApSuat")]
	public partial class ApSuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaA;
		
		private string _TenA;
		
		private EntitySet<DataContent> _DataContents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaAChanging(string value);
    partial void OnMaAChanged();
    partial void OnTenAChanging(string value);
    partial void OnTenAChanged();
    #endregion
		
		public ApSuat()
		{
			this._DataContents = new EntitySet<DataContent>(new Action<DataContent>(this.attach_DataContents), new Action<DataContent>(this.detach_DataContents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaA", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaA
		{
			get
			{
				return this._MaA;
			}
			set
			{
				if ((this._MaA != value))
				{
					this.OnMaAChanging(value);
					this.SendPropertyChanging();
					this._MaA = value;
					this.SendPropertyChanged("MaA");
					this.OnMaAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenA", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string TenA
		{
			get
			{
				return this._TenA;
			}
			set
			{
				if ((this._TenA != value))
				{
					this.OnTenAChanging(value);
					this.SendPropertyChanging();
					this._TenA = value;
					this.SendPropertyChanged("TenA");
					this.OnTenAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ApSuat_DataContent", Storage="_DataContents", ThisKey="MaA", OtherKey="IdA")]
		public EntitySet<DataContent> DataContents
		{
			get
			{
				return this._DataContents;
			}
			set
			{
				this._DataContents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DataContents(DataContent entity)
		{
			this.SendPropertyChanging();
			entity.ApSuat = this;
		}
		
		private void detach_DataContents(DataContent entity)
		{
			this.SendPropertyChanging();
			entity.ApSuat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VungKhiHau")]
	public partial class VungKhiHau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaV;
		
		private string _TenV;
		
		private EntitySet<DataContent> _DataContents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVChanging(string value);
    partial void OnMaVChanged();
    partial void OnTenVChanging(string value);
    partial void OnTenVChanged();
    #endregion
		
		public VungKhiHau()
		{
			this._DataContents = new EntitySet<DataContent>(new Action<DataContent>(this.attach_DataContents), new Action<DataContent>(this.detach_DataContents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaV", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaV
		{
			get
			{
				return this._MaV;
			}
			set
			{
				if ((this._MaV != value))
				{
					this.OnMaVChanging(value);
					this.SendPropertyChanging();
					this._MaV = value;
					this.SendPropertyChanged("MaV");
					this.OnMaVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenV", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string TenV
		{
			get
			{
				return this._TenV;
			}
			set
			{
				if ((this._TenV != value))
				{
					this.OnTenVChanging(value);
					this.SendPropertyChanging();
					this._TenV = value;
					this.SendPropertyChanged("TenV");
					this.OnTenVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VungKhiHau_DataContent", Storage="_DataContents", ThisKey="MaV", OtherKey="IdV")]
		public EntitySet<DataContent> DataContents
		{
			get
			{
				return this._DataContents;
			}
			set
			{
				this._DataContents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DataContents(DataContent entity)
		{
			this.SendPropertyChanging();
			entity.VungKhiHau = this;
		}
		
		private void detach_DataContents(DataContent entity)
		{
			this.SendPropertyChanging();
			entity.VungKhiHau = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DataContent")]
	public partial class DataContent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private string _IdV;
		
		private string _IdD;
		
		private string _IdN;
		
		private string _IdG;
		
		private string _IdA;
		
		private string _IdT;
		
		private EntityRef<ApSuat> _ApSuat;
		
		private EntityRef<VungKhiHau> _VungKhiHau;
		
		private EntityRef<DoAm> _DoAm;
		
		private EntityRef<Gio> _Gio;
		
		private EntityRef<NhietDo> _NhietDo;
		
		private EntityRef<ThoiTiet> _ThoiTiet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnIdVChanging(string value);
    partial void OnIdVChanged();
    partial void OnIdDChanging(string value);
    partial void OnIdDChanged();
    partial void OnIdNChanging(string value);
    partial void OnIdNChanged();
    partial void OnIdGChanging(string value);
    partial void OnIdGChanged();
    partial void OnIdAChanging(string value);
    partial void OnIdAChanged();
    partial void OnIdTChanging(string value);
    partial void OnIdTChanged();
    #endregion
		
		public DataContent()
		{
			this._ApSuat = default(EntityRef<ApSuat>);
			this._VungKhiHau = default(EntityRef<VungKhiHau>);
			this._DoAm = default(EntityRef<DoAm>);
			this._Gio = default(EntityRef<Gio>);
			this._NhietDo = default(EntityRef<NhietDo>);
			this._ThoiTiet = default(EntityRef<ThoiTiet>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdV", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdV
		{
			get
			{
				return this._IdV;
			}
			set
			{
				if ((this._IdV != value))
				{
					if (this._VungKhiHau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdVChanging(value);
					this.SendPropertyChanging();
					this._IdV = value;
					this.SendPropertyChanged("IdV");
					this.OnIdVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdD", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdD
		{
			get
			{
				return this._IdD;
			}
			set
			{
				if ((this._IdD != value))
				{
					if (this._DoAm.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdDChanging(value);
					this.SendPropertyChanging();
					this._IdD = value;
					this.SendPropertyChanged("IdD");
					this.OnIdDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdN", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdN
		{
			get
			{
				return this._IdN;
			}
			set
			{
				if ((this._IdN != value))
				{
					if (this._NhietDo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdNChanging(value);
					this.SendPropertyChanging();
					this._IdN = value;
					this.SendPropertyChanged("IdN");
					this.OnIdNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdG", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdG
		{
			get
			{
				return this._IdG;
			}
			set
			{
				if ((this._IdG != value))
				{
					if (this._Gio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdGChanging(value);
					this.SendPropertyChanging();
					this._IdG = value;
					this.SendPropertyChanged("IdG");
					this.OnIdGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdA", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdA
		{
			get
			{
				return this._IdA;
			}
			set
			{
				if ((this._IdA != value))
				{
					if (this._ApSuat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAChanging(value);
					this.SendPropertyChanging();
					this._IdA = value;
					this.SendPropertyChanged("IdA");
					this.OnIdAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdT", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdT
		{
			get
			{
				return this._IdT;
			}
			set
			{
				if ((this._IdT != value))
				{
					if (this._ThoiTiet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTChanging(value);
					this.SendPropertyChanging();
					this._IdT = value;
					this.SendPropertyChanged("IdT");
					this.OnIdTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ApSuat_DataContent", Storage="_ApSuat", ThisKey="IdA", OtherKey="MaA", IsForeignKey=true)]
		public ApSuat ApSuat
		{
			get
			{
				return this._ApSuat.Entity;
			}
			set
			{
				ApSuat previousValue = this._ApSuat.Entity;
				if (((previousValue != value) 
							|| (this._ApSuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ApSuat.Entity = null;
						previousValue.DataContents.Remove(this);
					}
					this._ApSuat.Entity = value;
					if ((value != null))
					{
						value.DataContents.Add(this);
						this._IdA = value.MaA;
					}
					else
					{
						this._IdA = default(string);
					}
					this.SendPropertyChanged("ApSuat");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VungKhiHau_DataContent", Storage="_VungKhiHau", ThisKey="IdV", OtherKey="MaV", IsForeignKey=true)]
		public VungKhiHau VungKhiHau
		{
			get
			{
				return this._VungKhiHau.Entity;
			}
			set
			{
				VungKhiHau previousValue = this._VungKhiHau.Entity;
				if (((previousValue != value) 
							|| (this._VungKhiHau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VungKhiHau.Entity = null;
						previousValue.DataContents.Remove(this);
					}
					this._VungKhiHau.Entity = value;
					if ((value != null))
					{
						value.DataContents.Add(this);
						this._IdV = value.MaV;
					}
					else
					{
						this._IdV = default(string);
					}
					this.SendPropertyChanged("VungKhiHau");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoAm_DataContent", Storage="_DoAm", ThisKey="IdD", OtherKey="MaD", IsForeignKey=true)]
		public DoAm DoAm
		{
			get
			{
				return this._DoAm.Entity;
			}
			set
			{
				DoAm previousValue = this._DoAm.Entity;
				if (((previousValue != value) 
							|| (this._DoAm.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DoAm.Entity = null;
						previousValue.DataContents.Remove(this);
					}
					this._DoAm.Entity = value;
					if ((value != null))
					{
						value.DataContents.Add(this);
						this._IdD = value.MaD;
					}
					else
					{
						this._IdD = default(string);
					}
					this.SendPropertyChanged("DoAm");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gio_DataContent", Storage="_Gio", ThisKey="IdG", OtherKey="MaG", IsForeignKey=true)]
		public Gio Gio
		{
			get
			{
				return this._Gio.Entity;
			}
			set
			{
				Gio previousValue = this._Gio.Entity;
				if (((previousValue != value) 
							|| (this._Gio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Gio.Entity = null;
						previousValue.DataContents.Remove(this);
					}
					this._Gio.Entity = value;
					if ((value != null))
					{
						value.DataContents.Add(this);
						this._IdG = value.MaG;
					}
					else
					{
						this._IdG = default(string);
					}
					this.SendPropertyChanged("Gio");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhietDo_DataContent", Storage="_NhietDo", ThisKey="IdN", OtherKey="MaN", IsForeignKey=true)]
		public NhietDo NhietDo
		{
			get
			{
				return this._NhietDo.Entity;
			}
			set
			{
				NhietDo previousValue = this._NhietDo.Entity;
				if (((previousValue != value) 
							|| (this._NhietDo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhietDo.Entity = null;
						previousValue.DataContents.Remove(this);
					}
					this._NhietDo.Entity = value;
					if ((value != null))
					{
						value.DataContents.Add(this);
						this._IdN = value.MaN;
					}
					else
					{
						this._IdN = default(string);
					}
					this.SendPropertyChanged("NhietDo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThoiTiet_DataContent", Storage="_ThoiTiet", ThisKey="IdT", OtherKey="MaT", IsForeignKey=true)]
		public ThoiTiet ThoiTiet
		{
			get
			{
				return this._ThoiTiet.Entity;
			}
			set
			{
				ThoiTiet previousValue = this._ThoiTiet.Entity;
				if (((previousValue != value) 
							|| (this._ThoiTiet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThoiTiet.Entity = null;
						previousValue.DataContents.Remove(this);
					}
					this._ThoiTiet.Entity = value;
					if ((value != null))
					{
						value.DataContents.Add(this);
						this._IdT = value.MaT;
					}
					else
					{
						this._IdT = default(string);
					}
					this.SendPropertyChanged("ThoiTiet");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoAm")]
	public partial class DoAm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaD;
		
		private string _TenD;
		
		private EntitySet<DataContent> _DataContents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDChanging(string value);
    partial void OnMaDChanged();
    partial void OnTenDChanging(string value);
    partial void OnTenDChanged();
    #endregion
		
		public DoAm()
		{
			this._DataContents = new EntitySet<DataContent>(new Action<DataContent>(this.attach_DataContents), new Action<DataContent>(this.detach_DataContents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaD", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaD
		{
			get
			{
				return this._MaD;
			}
			set
			{
				if ((this._MaD != value))
				{
					this.OnMaDChanging(value);
					this.SendPropertyChanging();
					this._MaD = value;
					this.SendPropertyChanged("MaD");
					this.OnMaDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenD", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string TenD
		{
			get
			{
				return this._TenD;
			}
			set
			{
				if ((this._TenD != value))
				{
					this.OnTenDChanging(value);
					this.SendPropertyChanging();
					this._TenD = value;
					this.SendPropertyChanged("TenD");
					this.OnTenDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoAm_DataContent", Storage="_DataContents", ThisKey="MaD", OtherKey="IdD")]
		public EntitySet<DataContent> DataContents
		{
			get
			{
				return this._DataContents;
			}
			set
			{
				this._DataContents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DataContents(DataContent entity)
		{
			this.SendPropertyChanging();
			entity.DoAm = this;
		}
		
		private void detach_DataContents(DataContent entity)
		{
			this.SendPropertyChanging();
			entity.DoAm = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gio")]
	public partial class Gio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaG;
		
		private string _TenG;
		
		private EntitySet<DataContent> _DataContents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGChanging(string value);
    partial void OnMaGChanged();
    partial void OnTenGChanging(string value);
    partial void OnTenGChanged();
    #endregion
		
		public Gio()
		{
			this._DataContents = new EntitySet<DataContent>(new Action<DataContent>(this.attach_DataContents), new Action<DataContent>(this.detach_DataContents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaG", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaG
		{
			get
			{
				return this._MaG;
			}
			set
			{
				if ((this._MaG != value))
				{
					this.OnMaGChanging(value);
					this.SendPropertyChanging();
					this._MaG = value;
					this.SendPropertyChanged("MaG");
					this.OnMaGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenG", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string TenG
		{
			get
			{
				return this._TenG;
			}
			set
			{
				if ((this._TenG != value))
				{
					this.OnTenGChanging(value);
					this.SendPropertyChanging();
					this._TenG = value;
					this.SendPropertyChanged("TenG");
					this.OnTenGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gio_DataContent", Storage="_DataContents", ThisKey="MaG", OtherKey="IdG")]
		public EntitySet<DataContent> DataContents
		{
			get
			{
				return this._DataContents;
			}
			set
			{
				this._DataContents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DataContents(DataContent entity)
		{
			this.SendPropertyChanging();
			entity.Gio = this;
		}
		
		private void detach_DataContents(DataContent entity)
		{
			this.SendPropertyChanging();
			entity.Gio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LogIn")]
	public partial class LogIn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDN;
		
		private string _Mk;
		
		private string _Role;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDNChanging(string value);
    partial void OnTenDNChanged();
    partial void OnMkChanging(string value);
    partial void OnMkChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    #endregion
		
		public LogIn()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDN", DbType="VarChar(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDN
		{
			get
			{
				return this._TenDN;
			}
			set
			{
				if ((this._TenDN != value))
				{
					this.OnTenDNChanging(value);
					this.SendPropertyChanging();
					this._TenDN = value;
					this.SendPropertyChanged("TenDN");
					this.OnTenDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mk", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Mk
		{
			get
			{
				return this._Mk;
			}
			set
			{
				if ((this._Mk != value))
				{
					this.OnMkChanging(value);
					this.SendPropertyChanging();
					this._Mk = value;
					this.SendPropertyChanged("Mk");
					this.OnMkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhietDo")]
	public partial class NhietDo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaN;
		
		private string _TenN;
		
		private EntitySet<DataContent> _DataContents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNChanging(string value);
    partial void OnMaNChanged();
    partial void OnTenNChanging(string value);
    partial void OnTenNChanged();
    #endregion
		
		public NhietDo()
		{
			this._DataContents = new EntitySet<DataContent>(new Action<DataContent>(this.attach_DataContents), new Action<DataContent>(this.detach_DataContents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaN", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaN
		{
			get
			{
				return this._MaN;
			}
			set
			{
				if ((this._MaN != value))
				{
					this.OnMaNChanging(value);
					this.SendPropertyChanging();
					this._MaN = value;
					this.SendPropertyChanged("MaN");
					this.OnMaNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenN", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string TenN
		{
			get
			{
				return this._TenN;
			}
			set
			{
				if ((this._TenN != value))
				{
					this.OnTenNChanging(value);
					this.SendPropertyChanging();
					this._TenN = value;
					this.SendPropertyChanged("TenN");
					this.OnTenNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhietDo_DataContent", Storage="_DataContents", ThisKey="MaN", OtherKey="IdN")]
		public EntitySet<DataContent> DataContents
		{
			get
			{
				return this._DataContents;
			}
			set
			{
				this._DataContents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DataContents(DataContent entity)
		{
			this.SendPropertyChanging();
			entity.NhietDo = this;
		}
		
		private void detach_DataContents(DataContent entity)
		{
			this.SendPropertyChanging();
			entity.NhietDo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rules")]
	public partial class Rule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _GT;
		
		private string _KL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnGTChanging(string value);
    partial void OnGTChanged();
    partial void OnKLChanging(string value);
    partial void OnKLChanged();
    #endregion
		
		public Rule()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GT", DbType="NVarChar(36) NOT NULL", CanBeNull=false)]
		public string GT
		{
			get
			{
				return this._GT;
			}
			set
			{
				if ((this._GT != value))
				{
					this.OnGTChanging(value);
					this.SendPropertyChanging();
					this._GT = value;
					this.SendPropertyChanged("GT");
					this.OnGTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KL", DbType="NVarChar(36) NOT NULL", CanBeNull=false)]
		public string KL
		{
			get
			{
				return this._KL;
			}
			set
			{
				if ((this._KL != value))
				{
					this.OnKLChanging(value);
					this.SendPropertyChanging();
					this._KL = value;
					this.SendPropertyChanged("KL");
					this.OnKLChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAPLUAT")]
	public partial class TAPLUAT
	{
		
		private string _dieuKien;
		
		private string _ketLuan;
		
		public TAPLUAT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dieuKien", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string dieuKien
		{
			get
			{
				return this._dieuKien;
			}
			set
			{
				if ((this._dieuKien != value))
				{
					this._dieuKien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ketLuan", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ketLuan
		{
			get
			{
				return this._ketLuan;
			}
			set
			{
				if ((this._ketLuan != value))
				{
					this._ketLuan = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThoiTiet")]
	public partial class ThoiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaT;
		
		private string _TenT;
		
		private EntitySet<DataContent> _DataContents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTChanging(string value);
    partial void OnMaTChanged();
    partial void OnTenTChanging(string value);
    partial void OnTenTChanged();
    #endregion
		
		public ThoiTiet()
		{
			this._DataContents = new EntitySet<DataContent>(new Action<DataContent>(this.attach_DataContents), new Action<DataContent>(this.detach_DataContents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaT", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaT
		{
			get
			{
				return this._MaT;
			}
			set
			{
				if ((this._MaT != value))
				{
					this.OnMaTChanging(value);
					this.SendPropertyChanging();
					this._MaT = value;
					this.SendPropertyChanged("MaT");
					this.OnMaTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenT", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string TenT
		{
			get
			{
				return this._TenT;
			}
			set
			{
				if ((this._TenT != value))
				{
					this.OnTenTChanging(value);
					this.SendPropertyChanging();
					this._TenT = value;
					this.SendPropertyChanged("TenT");
					this.OnTenTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThoiTiet_DataContent", Storage="_DataContents", ThisKey="MaT", OtherKey="IdT")]
		public EntitySet<DataContent> DataContents
		{
			get
			{
				return this._DataContents;
			}
			set
			{
				this._DataContents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DataContents(DataContent entity)
		{
			this.SendPropertyChanging();
			entity.ThoiTiet = this;
		}
		
		private void detach_DataContents(DataContent entity)
		{
			this.SendPropertyChanging();
			entity.ThoiTiet = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VUNG1")]
	public partial class VUNG1
	{
		
		private string _doAm;
		
		private string _nhietDo;
		
		private string _gio;
		
		private string _apSuat;
		
		private string _thoiTiet;
		
		public VUNG1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doAm", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string doAm
		{
			get
			{
				return this._doAm;
			}
			set
			{
				if ((this._doAm != value))
				{
					this._doAm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhietDo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string nhietDo
		{
			get
			{
				return this._nhietDo;
			}
			set
			{
				if ((this._nhietDo != value))
				{
					this._nhietDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gio", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string gio
		{
			get
			{
				return this._gio;
			}
			set
			{
				if ((this._gio != value))
				{
					this._gio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apSuat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string apSuat
		{
			get
			{
				return this._apSuat;
			}
			set
			{
				if ((this._apSuat != value))
				{
					this._apSuat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiTiet", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string thoiTiet
		{
			get
			{
				return this._thoiTiet;
			}
			set
			{
				if ((this._thoiTiet != value))
				{
					this._thoiTiet = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VUNG2")]
	public partial class VUNG2
	{
		
		private string _doAm;
		
		private string _nhietDo;
		
		private string _gio;
		
		private string _apSuat;
		
		private string _thoiTiet;
		
		public VUNG2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doAm", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string doAm
		{
			get
			{
				return this._doAm;
			}
			set
			{
				if ((this._doAm != value))
				{
					this._doAm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhietDo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string nhietDo
		{
			get
			{
				return this._nhietDo;
			}
			set
			{
				if ((this._nhietDo != value))
				{
					this._nhietDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gio", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string gio
		{
			get
			{
				return this._gio;
			}
			set
			{
				if ((this._gio != value))
				{
					this._gio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apSuat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string apSuat
		{
			get
			{
				return this._apSuat;
			}
			set
			{
				if ((this._apSuat != value))
				{
					this._apSuat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiTiet", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string thoiTiet
		{
			get
			{
				return this._thoiTiet;
			}
			set
			{
				if ((this._thoiTiet != value))
				{
					this._thoiTiet = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VUNG3")]
	public partial class VUNG3
	{
		
		private string _doAm;
		
		private string _nhietDo;
		
		private string _gio;
		
		private string _apSuat;
		
		private string _thoiTiet;
		
		public VUNG3()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doAm", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string doAm
		{
			get
			{
				return this._doAm;
			}
			set
			{
				if ((this._doAm != value))
				{
					this._doAm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhietDo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string nhietDo
		{
			get
			{
				return this._nhietDo;
			}
			set
			{
				if ((this._nhietDo != value))
				{
					this._nhietDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gio", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string gio
		{
			get
			{
				return this._gio;
			}
			set
			{
				if ((this._gio != value))
				{
					this._gio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apSuat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string apSuat
		{
			get
			{
				return this._apSuat;
			}
			set
			{
				if ((this._apSuat != value))
				{
					this._apSuat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiTiet", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string thoiTiet
		{
			get
			{
				return this._thoiTiet;
			}
			set
			{
				if ((this._thoiTiet != value))
				{
					this._thoiTiet = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VUNG4")]
	public partial class VUNG4
	{
		
		private string _doAm;
		
		private string _nhietDo;
		
		private string _gio;
		
		private string _apSuat;
		
		private string _thoiTiet;
		
		public VUNG4()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doAm", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string doAm
		{
			get
			{
				return this._doAm;
			}
			set
			{
				if ((this._doAm != value))
				{
					this._doAm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhietDo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string nhietDo
		{
			get
			{
				return this._nhietDo;
			}
			set
			{
				if ((this._nhietDo != value))
				{
					this._nhietDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gio", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string gio
		{
			get
			{
				return this._gio;
			}
			set
			{
				if ((this._gio != value))
				{
					this._gio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apSuat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string apSuat
		{
			get
			{
				return this._apSuat;
			}
			set
			{
				if ((this._apSuat != value))
				{
					this._apSuat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiTiet", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string thoiTiet
		{
			get
			{
				return this._thoiTiet;
			}
			set
			{
				if ((this._thoiTiet != value))
				{
					this._thoiTiet = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VUNG5")]
	public partial class VUNG5
	{
		
		private string _doAm;
		
		private string _nhietDo;
		
		private string _gio;
		
		private string _apSuat;
		
		private string _thoiTiet;
		
		public VUNG5()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doAm", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string doAm
		{
			get
			{
				return this._doAm;
			}
			set
			{
				if ((this._doAm != value))
				{
					this._doAm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhietDo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string nhietDo
		{
			get
			{
				return this._nhietDo;
			}
			set
			{
				if ((this._nhietDo != value))
				{
					this._nhietDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gio", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string gio
		{
			get
			{
				return this._gio;
			}
			set
			{
				if ((this._gio != value))
				{
					this._gio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apSuat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string apSuat
		{
			get
			{
				return this._apSuat;
			}
			set
			{
				if ((this._apSuat != value))
				{
					this._apSuat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiTiet", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string thoiTiet
		{
			get
			{
				return this._thoiTiet;
			}
			set
			{
				if ((this._thoiTiet != value))
				{
					this._thoiTiet = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
